/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

currentTerm = 0;
oneTermAgo = 0;
twoTermsAgo = 0;

function fib(limit){
  while (currentTerm < limit){
    if(currentTerm < 1){
      oneTermAgo = currentTerm;
      currentTerm++;
      console.log("Current number in the sequence: " + currentTerm + "\n");
    }else if(currentTerm == 1){
      oneTermAgo = currentTerm;
      currentTerm = currentTerm + oneTermAgo;
      console.log("Previous number in the sequence: " + oneTermAgo)
      console.log("Current number in the sequence: " + currentTerm + "\n");
    }else{
      twoTermsAgo = oneTermAgo;
      oneTermAgo = currentTerm;
      currentTerm = oneTermAgo + twoTermsAgo;
      console.log("Two numbers ago in the sequence: " + twoTermsAgo);
      console.log("One number ago in the sequence: " + oneTermAgo);
      console.log("Current number in the sequence: " + currentTerm + "\n");
    }

  }
}


console.log(fib(10));
